Repository QingFeng-awa/AuModSite, pull requests merged in 2024-07, with the labels that each got.

#2 Update English
  Mods/Host/TownOfHost.md
  en/Host/TownOfHost.md
  en/Host/index.md
  en/index.md
Labels: 优化, 新增

#7 小更新
  Authors/KARPED1EM.md
  en/Authors/KARPED1EM.md
  en/Contributing.md
  en/Mods/Functional/index.md
  en/Mods/Host/TownOfHostPlus.md
Labels: 类型:优化, dev

#14 修复图片问题和添加英文翻译以及部分更改
  .vitepress/config.mts
  Contributing.md
  Mods/Functional/YuAntiCheat.md
  Mods/NoHost/TheOtherRoles.md
  Mods/NoHost/TownOfUs.md
  en/Authors/KARPED1EM.md
  en/Contributing.md
  en/Mods/Functional/YuAntiCheat.md
  en/Mods/Host/TownOfHost.md
  en/Mods/Host/TownOfHostEdited.md
  en/Mods/Host/TownOfHostEnhanced.md
  en/Mods/Host/TownOfNewEpic_Xtreme.md
  en/Mods/Host/TownOfNext.md
  en/Mods/NoHost/TheOtherRoles.md
  en/Mods/NoHost/TownOfUs.md
  en/donate.md
  public/Image/LezaiYa1.png
  public/Image/Slushie.png
  public/Image/TheOtherRoles.png
  public/Image/TownOfUs.png
  public/Image/Yu.png
  public/Image/YuAC.jpg
  public/Image/twix.png
Labels: 类型:优化, 类型:需求, dev

#16 It's Time To Be A [[BIG SHOT]]!!!
  .gitignore
  .vitepress/config.mts
  Authors/index.md
  Mods/AllClient/TheOtherRoles.md
  Mods/AllClient/TownOfUs.md
  Mods/AllClient/index.md
  Mods/Functional/index.md
  Mods/HostOnly/TownOfHost.md
  Mods/HostOnly/TownOfHostEdited.md
  Mods/HostOnly/TownOfHostEnhanced.md
  Mods/HostOnly/TownOfHostPlus.md
  Mods/HostOnly/TownOfNewEpic_Xtreme.md
  Mods/HostOnly/TownOfNext.md
  Mods/HostOnly/index.md
  Mods/NoHost/index.md
  en/Authors/index.md
  en/Mods/Functional/index.md
  en/index.md
  index.md
Labels: 类型:优化

#19 回退
  .vitepress/config.mts
  Authors/Loonie.md
  Authors/Moe.md
  Mods/AllClient/LasMonjas.md
  Mods/Functional/MalumMenu.md
  Mods/Functional/YuAntiCheat.md
  en/Authors/Loonie.md
  en/Authors/Moe.md
  en/Mods/AllClient/LasMonjas.md
  en/Mods/AllClient/index.md
  en/Mods/Functional/MalumMenu.md
  en/Mods/Functional/YuAntiCheat.md
  en/Mods/Host/TownOfHost.md
  en/Mods/Host/TownOfHostEdited.md
  en/Mods/Host/TownOfHostEnhanced.md
  en/Mods/Host/TownOfHostPlus.md
  en/Mods/Host/TownOfNewEpic_Xtreme.md
  en/Mods/Host/TownOfNext.md
  en/Mods/Host/index.md
  en/Mods/HostOnly/index.md
  en/Mods/NoHost/TheOtherRoles.md
  en/Mods/NoHost/TownOfUs.md
  en/Mods/NoHost/index.md
  en/index.md
  public/Image/KiraYamato94.png
  public/Image/LasMonjas_banner.png
  public/Image/MalumMenu.png
  public/Image/scp222thj.png
Labels: 优先处理

#21 好吧，这只是文字上的问题，lol
  .vitepress/config.mts
Labels: 类型:优化, dev

#27 添加英文翻译 & 删除没用的图片
  .vitepress/config.mts
  Mods/Functional/YuAntiCheat.md
  en/Mods/AllClient/LasMonjas.md
  en/Mods/AllClient/NebulaOnTheShip.md
  en/Mods/AllClient/StellarRoles.md
  en/Mods/AllClient/SuperNewRoles.md
  en/Mods/AllClient/TheOtherRoles.md
  en/Mods/AllClient/TownOfUs.md
  en/Mods/AllClient/TownOfUsR.md
  en/Mods/AllClient/index.md
  en/Mods/Functional/MalumMenu.md
  en/Mods/Functional/YuAntiCheat.md
  en/Mods/HostOnly/EndlessHostRoles.md
  en/Mods/HostOnly/TownOfChaos.md
  en/Mods/HostOnly/TownOfCrew：SeaOfShark.md
  en/Mods/HostOnly/TownOfHost.md
  en/Mods/HostOnly/TownOfHostEdited.md
  en/Mods/HostOnly/TownOfHostEditedXi.md
  en/Mods/HostOnly/TownOfHostEnhanced.md
  en/Mods/HostOnly/TownOfHostPlus.md
  en/Mods/HostOnly/TownOfHost_Y.md
  en/Mods/HostOnly/TownOfNewEpic_Xtreme.md
  en/Mods/HostOnly/TownOfNext.md
  en/Mods/HostOnly/TownOfPlus.md
  en/Mods/HostOnly/index.md
  en/guide/FAQ/GithubError.md
  en/guide/index.md
  en/guide/tutorial/install/Steam.md
  en/index.md
  public/Image/Glaceon.jpg
  public/Image/Kuki.png
  public/Image/KuratoTsukishiro.png
  public/Image/Masami.jpg
  public/Image/Slushie.png
  public/Image/TAKU_GG.jpg
  public/Image/Tanakarina.png
  public/Image/TownOfHostEditedXi.jpg
  public/Image/UKONpeople.jpg
  public/Image/kihi.jpg
  public/Image/こう。.png
  public/Image/しゅー.jpg
  public/Image/じゅき.jpg
  public/Image/そうくん.jpg
  public/Image/たんぽぽ.png
  public/Image/はいず.png
  public/Image/みぃー.png
  public/Image/ゆりの.png
Labels: 类型:优化, dev
